#!/bin/bash
input_file="mtcars${SLURM_ARRAY_TASK_ID}.csv"

awk -F ',' '{

    if (NR == 1) {
        print $2 > "out'"${SLURM_ARRAY_TASK_ID}"'.csv"
    } else {

        if ($2 == 3) {
            print $10 > "out'"${SLURM_ARRAY_TASK_ID}"'.csv"
        }
    }
}' "$input_file"

